### PR TITLE
Issue 55 suggestions

### PR DESCRIPTION
**Pull request by sushain97**

### CODE REVIEW

**Comment by sushain97** [comment]
@Androbin, I'm not sure why 1) this is so conflicted 2) the diff is massive...

**Comment by Androbin** [comment]
@sushain97 I thought so, too?
The "Conflicting files" are the same as before I de-conflicted them.

**Comment by Androbin** [comment]
I find it very strange that it shows changes that already are on `master`...

**Comment by Androbin** [comment]
Could this be due to the merge commit having `master` as mainstream parent but the PR based against `issue-55-suggestions` ?

**Comment by Androbin** [comment]
The merge conflict should be easy to resolve since all changes are already de-conflicted.
Meaning for a given conflict, the `issue-55-suggestions` version is always the way to go.
If you give me a minute, I'll send another PR, deconflicted.

**Comment by Androbin** [comment]
Okay, let's continue with #251.

**Comment by Androbin** [comment]
@sushain97 The problem was that by squashing the other PR, you destroyed all merge information.

**Pull request closed without merging**
