### PR TITLE
Website translation

### PR DESCRIPTION
**Pull request by sushain97**

### CODE REVIEW

**Comment by jonorthwash** [comment]
A few things I've noticed:
- It doesn't seem to accept a second url after it does one.
- It doesn't seem to follow urls in translated pages (maybe just relative ones?).
- Perhaps it should add or assume "http://" or something by default if not given?

**Comment by sushain97** [comment]
@jonorthwash,

> It doesn't seem to accept a second url after it does one.
I can't duplicate this one. Anything in the JS console?

> It doesn't seem to follow urls in translated pages (maybe just relative ones?).
This should be a new feature, let's open an issue for it after we get this through :)

> Perhaps it should add or assume "http://" or something by default if not given?
I'll see how I can improve the behavior here.

**Comment by jonorthwash** [comment]
> > It doesn't seem to accept a second url after it does one.

> I can't duplicate this one. Anything in the JS console?

This seems to be a sporadic refusal to work.  Just now it refused to translate anything (no turny dots even) until I switched from kaz-tat to another pair.  But when I switched back to kaz-tat, it was happy again.

> > It doesn't seem to follow urls in translated pages (maybe just relative ones?).

> This should be a new feature, let's open an issue for it after we get this through :)

Seems like a feature people are going to expect.  But yeah, from a development point of view, that makes sense :)

> > Perhaps it should add or assume "http://" or something by default if not given?

> I'll see how I can improve the behavior here.

Awesome.

**Comment by sushain97** [comment]
As a reminder to myself, there are still issues with scripts, stylesheets and images using relative URLs. I'll try experimenting more with `<base>` which _should_ work. Further, APy seems to be modifying the HTML to fix relative URLs for `<a>` tags using a regexp. APy shouldn't do this either way. If we need to do it, it should be done client side so we have a clean API. The same applies to APy's regexp transformation of links which may destroy existing handlers and is possible in JS.

**Comment by sushain97** [comment]
link to #83

**Comment by unhammer** [comment]
btw https://github.com/goavki/apertium-html-tools/tree/websiteTranslationGiellatekno is running at http://gtweb.uit.no/jorgal/ with some changes possible improvements – not all of which we want in apertium.org :)

**Comment by share-with-me** [comment]
> As a reminder to myself, there are still issues with scripts, stylesheets and images using relative URLs. I'll try experimenting more with <base> which should work. Further, APy seems to be modifying the HTML to fix relative URLs for <a> tags using a regexp. APy shouldn't do this either way. If we need to do it, it should be done client side so we have a clean API. The same applies to APy's regexp transformation of links which may destroy existing handlers and is possible in JS.


@sushain97 , is this the issue that has to be resolved before making it ready for merging? I have checked out the branches `websiteTranslation` and `giellatekno`, ran the feature on the localhost and also understood the code of how `iframe` is populating the contents of the translated Webpage and how `base` is working to ensure that all the links in the `iframe` div point to the `URL`. (loved the feature :D) What are the other issues that need to be resolved with respect to this feature?

**Comment by sushain97** [comment]
> What are the other issues that need to be resolved with respect to this feature?

There may be other things. This is part of your job to figure out!

**Comment by share-with-me** [comment]
@jonorthwash 

> It doesn't seem to accept a second url after it does one.

Does this issue still exist? I am unable to reproduce this.

@sushain97 
A few issues that I found ( just putting them up as I have found):

1. Relative URLs in translated web pages do not seem to point to the correct location (as addressed).
2. If `http:// or https://` is not provided, it throws an `internal service 500` error.
3. For a few sites like `stackoverflow`, when I type in the URL, I get the following warning in `alert` after which a lot of it breaks in the console. Perhaps, we should handle such security warnings more gracefully and let the user know that the translation will not be possible? ( cannot expect users to open console and realise it!)

screen shot 2017-06-15 at 9 30 02 am

screen shot 2017-06-15 at 9 30 27 am


4. For a website - `http://www.bbc.co.uk/blogs/learningenglish`, I get an error in the console - 
'syntax error - missing ) after argument list'

screen shot 2017-06-15 at 9 31 21 am

5. For websites - `https://github.com/goavki/apertium-html-tools/pull/139` and a few others, I get the error - `Proxy Error - 502` like the following. Um, I did not understand why this error happens in the first place. If this happens, should we let the user know through some alert or warning that it is not possible to fetch the translation? Again, we cannot expect users to open console and realise that there has been an error!! This applies for all, in case, translation is not possible ( due to any reason ), we  notify the user of the same (possibly with the reason?!) - perhaps - `translation not available due to...`!

screen shot 2017-06-15 at 9 49 35 am

6. For website - `http://www.apertium.org`, I am unclear why it throws `Security` error like the following. (Cookies enabled in my browser) Does populating `iframes` with other URL contents that use `localStorage or sessionStorage` give this error? - will look into!! If this happens, again, this needs to be gracefully handled for the user!

screen shot 2017-06-15 at 9 59 42 am

7. Lastly, would it make sense to provide functionality where users could clear the contents of the populated `iframe`? Make it blank with url null or something like that?

**Comment by sushain97** [comment]
> Relative URLs in translated web pages do not seem to point to the correct location (as addressed).

Yep. This one is tricky to fix. Might require changes to APy.

> If http:// or https:// is not provided, it throws an internal service 500 error.

The `type="url"` of the `input` box should prevent that from even being submitted?

> For a few sites like stackoverflow, when I type in the URL, I get the following warning in alert after which a lot of it breaks in the console. Perhaps, we should handle such security warnings more gracefully and let the user know that the translation will not be possible? ( cannot expect users to open console and realise it!)

What does Google Translate do?

> For websites - https://github.com/goavki/apertium-html-tools/pull/139 and a few others, I get the error - Proxy Error - 502 like the following. 

Same as above and for the others. I'm not sure about why the errors are occurring :) @unhammer may have some insights from implementing the other version of this feature.

> Lastly, would it make sense to provide functionality where users could clear the contents of the populated iframe? Make it blank with url null or something like that?

I don't think this is necessary.

**Comment by unhammer** [comment]
I hadn't seen the SecurityError, but I think it's going to be hard anyway to acheive the full javascript functionality of the original site when shown from a different domain (all kinds of cross-domain stuff comes into play here). And I wouldn't worry too much about the feature of showing apertium in apertium :-)

**Comment by unhammer** [comment]
Regarding url-rewriting, does this happen on jorgal.uit.no too? 

Have you checked if any changes from the giellatekno branch should go back to this one?

**Comment by share-with-me** [comment]
@sushain97 

> What does Google Translate do?

Google Translate too, gives that same alert. However, that was momentary and the page got translated successfully after that. Things in console did not break!

> The type="url" of the input box should prevent that from even being submitted?

Ohh!

@unhammer ,

> I hadn't seen the SecurityError, but I think it's going to be hard anyway to acheive the full javascript functionality of the original site when shown from a different domain (all kinds of cross-domain stuff comes into play here).

Yes, cross-domain stuff would be tough to achieve. But I was thinking of an approach where if, for any reason ( be it security error, service unavailable, proxy error, etc. ), the translation fails, we could notify the user.

> And I wouldn't worry too much about the feature of showing apertium in apertium :-)

:D. I was just playing around with the feature :P. It was fun and I was just trying totally random stuff.

> Regarding the url-rewriting bugs you found, does this happen on http://jorgal.uit.no too? Have you checked if any changes from the giellatekno branch should go back to this one?

I will start working on it at EOD ( as soon as reach home. ) Not checked on this yet!

**Comment by jonorthwash** [comment]
> > It doesn't seem to accept a second url after it does one.
> Does this issue still exist? I am unable to reproduce this.

I can't tell—the feature seems to've been disabled on the main apertium.org site...

**Comment by unhammer** [comment]
Jonathan Washington <notifications@github.com> čálii:

>  It doesn't seem to accept a second url after it does one.
>  Does this issue still exist? I am unable to reproduce this.
>
> I can't tell—the feature seems to've been disabled on the main apertium.org site...

What about on http://jorgal.uit.no ?

**Comment by share-with-me** [comment]
Currently, if the URL field is blank, we get the following errors in `websiteTranslation` branch and `http://jorgal.uit.no ` site.

**1. websiteTranslation**

websiteurlblank

**2. jorgal**

screenshot from 2017-06-19 15-24-47

 Would it make sense to not allow the function to even execute if the URL field is blank?

**Comment by share-with-me** [comment]
@sushain97 , Um, If I wish to modify this PR, how do I do it? You are the owner of this PR right? How do I merge my changes into this PR?

**Comment by jonorthwash** [comment]
> > > >  It doesn't seem to accept a second url after it does one.
> > >
> > >  Does this issue still exist? I am unable to reproduce this.
> > 
> > I can't tell—the feature seems to've been disabled on the main apertium.org site...
>
> What about on http://jorgal.uit.no ?

I was having trouble getting any website translation at all to work there...

**Comment by unhammer** [comment]
it's mostly tested on the few Saami sites there are ;)
http://gtweb.uit.no/jorgal/index.nob.html?dir=sme-nob&qP=https%3A%2F%2Fwww.nrk.no%2Fsapmi%2Fdavvisamegillii%2F#webpageTranslation

(that branch of apy even does pdftotext:
http://gtweb.uit.no/jorgal/index.nob.html?dir=sme-nob&qP=http%3A%2F%2Fsite.uit.no%2Faigecala%2Ffiles%2F2013%2F03%2FSDA_2-2012.pdf#webpageTranslation )

**Comment by unhammer** [comment]
@share-with-me no, there should be a more helpful error message on empty urls :)

**Comment by share-with-me** [comment]
@unhammer Sure!

**Comment by share-with-me** [comment]
@unhammer , In live version at [ http://jorgal.uit.no]( http://jorgal.uit.no), when I pass in erroneous value as URL ( eg: cfcfcfc ), it shows an error that translation is not available! Now, when I press the `Cancel/Back` button to go back to translation Interface:
1. The error remains persistent at right edge of the webpage ( screenshot below)
2. Even on clicking the Cancel button, the `translateWebpage` function gets called one more time - can be seen in console (screenshot below)

screenshot from 2017-06-19 20-47-41

**Comment by sushain97** [comment]
@share-with-me I think @unhammer meant that there ought to be a better error, not that there is one already.

The jorgal version of html-tools has diverged from upstream so it's not of much use to dissect its possible shortcoming. Hopefully, we can deliver a more robust solution here and @unhammer can merge in :)

**Comment by sushain97** [comment]
> @sushain97 , Um, If I wish to modify this PR, how do I do it? You are the owner of this PR right? How do I merge my changes into this PR?

Checkout this branch and develop on top of it.

**Comment by share-with-me** [comment]
@sushain97 , 

> The type="url" of the input box should prevent that from even being submitted?

I modified the code to `<input type="submit" ...>` from `<button type="button" ...>` and now when I click on the `Translate` button, it behaves as desired!

**Comment by unhammer** [comment]
Yeah, the reason I wanted you to take a look at the giellatekno branch was mainly if there was stuff there that should be merged into websiteTranslation.

**Comment by share-with-me** [comment]
@unhammer , your code in giellatekno branch is helping me a lot :D. I am using up that code, making possible improvements what I can think of and developing this feature for master branch :D.

**Comment by unhammer** [comment]
(I edited the above comment in case you didn't notice before your last comment)

**Comment by share-with-me** [comment]
Had a look :). Thanks @unhammer

**Pull request closed without merging**
