### PR TITLE
Website translation

### PR DESCRIPTION
**Pull request by share-with-me**
I have made use of Enter handler instead of submit form handler. This (currently) has resolved the following issue:

- spurious "translation not available" occurs on document translation cancel, also failed translation request.

Apart from this, the issue of page refresh with URL containing hash and not translating has been fixed.

Thus, the only issue left to be fixed (which I shall on this PR):

- Appropriate CSS for `srcLangSelectors` so that they take up the available space for them.

### CODE REVIEW

**Comment by sushain97** [comment]
@share-with-me can you branch off of `origin/websiteTranslation2` and then `git cherry-pick 
6fb969b...a4bcbdf` and PR that so that the diff is more readable?

**Comment by share-with-me** [comment]
Um, sorry for this @sushain97 but you could you tell the commands? 

Should I change the upstream ie. the branch I am pushing it to? (Could you tell the commands :/)

**Comment by sushain97** [comment]
```
git fetch
git checkout -b monishTranslation websiteTranslation2
git cherry-pick 6fb969b...a4bcbdf
git push
```

then create the PR on Github with base branch as `websiteTranslation2`.

**Comment by share-with-me** [comment]
Ohh! Thanks. I'd do it now.

**Pull request closed without merging**
