### PR TITLE
Changed GET to POST in translateText() function

### PR DESCRIPTION
**Pull request by share-with-me**
Added this functionality currently only in translateText() function. This now ensures that the user can supply large texts in input text box and he wont get 414 error.
Will add this across generator, morphological analysis and analyser mode once I get comfortable with their functioning.

### CODE REVIEW

**Comment by share-with-me** [comment]
The code yields the following functionality:
screen shot 2017-03-13 at 5 01 15 pm

**Comment by unhammer** [comment]
We only want POST requests on long strings – short ones should still go over GET using jsonp, cf https://github.com/goavki/apertium-html-tools/issues/79#issuecomment-286061122

**Comment by share-with-me** [comment]
@unhammer , Ohh Alright! So as this [stackoverflow](http://stackoverflow.com/questions/266322/is-there-a-limit-to-the-length-of-a-get-request) post says, I will keep a threshold for this length around 2000 chars. Anything more than that, I will use $.ajax instead $.post !

**Comment by share-with-me** [comment]
@unhammer  I have added the functionality where larger texts will use $.ajax() and smaller texts will use $.jsonp() as originally used. Screenshots are attached below. The last lines in each cosole image describe the method that is used.
screen shot 2017-03-13 at 5 46 05 pm
screen shot 2017-03-13 at 5 46 36 pm

**Comment by sushain97** [comment]
I would approach implementing this by creating a new function that simply wraps over both `ajax` and `jsonp`, taking a second parameter that indicates the size of the request. Then, this function will send the request. This will make it more DRY especially when you're extending to the other modes.

Also, make sure to take a look at the Travis/Hound violations/build failures on this PR and others.

Good work!

**Comment by share-with-me** [comment]
@sushain97  Yes, surely! I tried to resolve some hound and travis errors. Huff, they are good error pointers :P . However, I will first focus on achieving the functionality and then in a while, solve these errors too. As for the DRY philosophy, on it. I will wrap this function and then call the appropriate method. Thanks for motivating! :D

**Comment by share-with-me** [comment]
Closing this PR as I've created a refactored PR in a separate branch!

**Pull request closed without merging**
