### PR TITLE
Initial code for a visual chained translation path selector

### PR DESCRIPTION
**Pull request by shardulc**
Add a button which opens a modal with a graph of the possible paths from the selected source to the selected destination. The button is visible only when the multi-step checkbox is checked. The modal has a rudimentary 'Valid Paths' section with links to select the path: this works, but I'm not good at UI so I'm requesting help. Many of the strings/UI might require change anyway. (Uses d3.) (Ref #91)

### CODE REVIEW

**Comment by sushain97** [comment]
@shardulc thanks for working on this!! I will take a look soon hopefully :)

**Comment by share-with-me** [comment]
This feature is awesome :D . I have myself worked quite a bit on d3.js and I would love to take up this feature. Is there some working demo or some visualisation of this d3 code? 
In the description of this issue, it says it has a section of Valid Paths. How do we know that? Is some analysis taking place in the backend which generates a list of valid paths (some graphs/DFS stuff?) ?

**Comment by sushain97** [comment]
The analysis takes place in APy. I believe it's Dijkstra's.

The feature itself is quite cool. You can checkout this PR and try it out!

**Comment by shardulc** [comment]
@share-with-me As @sushain97 said, the default path selection for chained translation is done in APy (specifically [here](https://github.com/goavki/apertium-apy/blob/master/servlet.py#L144)) which is currently just Dijkstra's with equal weights for all pairs. There is a small chance of the weights being significant in the future if we have a good metric for pair quality. However, all possible paths cannot and should not be sent to clients because that is easily computable from just a list of pairs (and potentially weights), so on the html-tools side, there is BFS ([here](https://github.com/shardulc/apertium-html-tools/blob/6996354c977feac8ddb0f2873a5a2ae153f029af/assets/js/translator.js#L355)).

The 'Valid Paths' referred to are basically just paths which include almost all (actually at least all but one) of the nodes that a user selects and go from the source to the destination. This is also easy to compute.

d3 is really cool! Please do checkout this PR and try it out, we can discuss any suggestions/contributions you have.

**Comment by shardulc** [comment]
[Things discussed](http://tinodidriksen.com/pisg/freenode/logs/%23apertium_20170314.log) in `#apertium` on 2017-03-14 at 03:01:11 for around an hour:

- [ ] Modal should have default path already chosen
- [ ] The button should say "refine current path" or something similar, and should have a hover icon
- [ ] 'Valid Paths' should be more prominently displayed, with placeholder text advising users if there are no valid paths
- [ ] Only the relevant arrowheads should be displayed instead of all available ones

**Comment by shardulc** [comment]
I tried to add everything in the checklist from the previous comment, but I just had two questions:
1. What should the 'hover icon' look like?
2. Instead of placeholder text when there is no path selected, the modal starts out with the Valid Paths section indicating the default path, and if the user selects anything, the default path goes away.

**Comment by sushain97** [comment]
^ looks like there are a couple conflicts :(

**Pull request merged**
