### PR TITLE
Installation notification (progress on #83)

### PR DESCRIPTION
**Pull request by sushain97**

### CODE REVIEW

**Comment by sushain97** [comment]
@share-with-me I moved here so that we could start the conversation afresh and get rid of the long thread. I made some modifications, primarily some code cleanup. Taking another look, is it necessary to have both a count of requests made and array that contains the request times? It seems like it would be possible to simply take its length.

I don't think the fade is working when I do:

```
installationNotificationShown = false; 
displayInstallationNotification()
```

Also, could you up the size of the alert text a bit? It seems smaller than normal body text. And some padding between the header and text would go a long way towards cleaning it up.

**Comment by share-with-me** [comment]
> is it necessary to have both a count of requests made and array that contains the request times? It seems like it would be possible to simply take its length.

Um, how would you calculate the average of the requests then? I think am not clear with your point. We maintain a queue of request times that helps us to keep the track of average of latest `MAX(numRequests, INSTALLATION_BUFFER)` number of requests!

> I don't think the fade is working when I do:

Um, could you tell where exactly you are executing `displayInstallationNotification()`? I tried in the `callApy()` and on page load, and it does work as expected!

> Also, could you up the size of the alert text a bit? It seems smaller than normal body text. And some padding between the header and text would go a long way towards cleaning it up.

On it :D

**Comment by sushain97** [comment]
> maintain a queue of request times

This queue has a length.

**Comment by share-with-me** [comment]
> This queue has a length.

Ah! makes sense. I misinterpreted it! Will change it now :D

**Comment by share-with-me** [comment]
Um, @sushain97  I checked out this branch and made the necessary changes! I did a `git push origin installationNotification`, and that prompted me to create new PR. Is there a way I can push to this PR?

**Comment by sushain97** [comment]
Not really. Creating a new one is fine.

**Comment by share-with-me** [comment]
Closing here and continuing on #164

**Pull request closed without merging**
