### PR TITLE
Mark multi-step destinations

### LINKED ISSUE #120: mark destinations through multi-step translation somehow
Currently when multi-step is enabled, only the option says "experimental" and not the translation destination languages.  We should have some way of indicating that these are experimental "pairs".

### PR DESCRIPTION
**Pull request by shardulc**
Marks multi-step destinations with a '+' sign, explanation string added only for English. (Attempt to fix #120)

### CODE REVIEW

**Comment by sushain97** [comment]
Mind throwing up some screenshots to make this stuff easier to make suggestions on? Running an APy instance that actually supports multi-step translation with enough pairs to make the graph meaningful can be a little annoying ;)

**Comment by shardulc** [comment]
Here's a screenshot with multi-step translation between all pairs supported on the Apertium APy instance.

image

**Comment by sushain97** [comment]
Hm, okay. I think it makes sense for the non-multi-step target languages to come first. Thoughts? @jonorthwash 

Also, I'm not super sold on the "+". Maybe some sort of a symbol? Arrow with two marks on it? Something that looks like an angle symbol? Unsure. The plus is a bit confusing though.

**Comment by shardulc** [comment]
I agree that the direct targets should come first. For the symbol, do you think there could be a non-symbol way of representing it (a bad example is coloring the text)?

**Comment by sushain97** [comment]
Unfortunately, nothing great comes to mind immediately. What might be really cool is showing the path that the translation takes when you hover over the symbol in a tooltip.

**Comment by shardulc** [comment]
Updated screenshot, still using '+'.
image

**Comment by jonorthwash** [comment]
I also don't like the '+'.  It has connotations of "better" or "more advanced", which in this case is false.  I'd prefer '(-_n_)' (in red even), where _n_ is the number of steps it has to go through.

**Comment by shardulc** [comment]
Updated screenshots:

screenshot0

screenshot1

What should the checkbox text say instead of "experimental, marked with +"? Talking about weights isn't for everyone?

**Comment by shardulc** [comment]
To get the weights from APy, it currently makes the request `/listPairs?q=pairs&weights=yes`, which is what the APy endpoint should be in the future if weights are supported.

**Comment by sushain97** [comment]
It's looking much better. Some suggestions:

- We need fewer colors. Even if had a key, the current number is a bit too high. Maybe we can make the light blue edges the same gray as the arrows? 
- It doesn't seem that we've highlighted the edges in valid paths as a different color than the current selected path?
- I think we can omit the (-3) on the valid paths list. It's somewhat obvious. Maybe also sort by weight, i.e. the shortest ones first now.
- The tooltip in the destination list doesn't have the little caret that indicates where it came from? It seems randomly placed.

**Comment by jonorthwash** [comment]
I agree with everything @sushain97 said but one thing:

I like the indications of how long the path is, like (-3).  I also think the valid paths should be sorted in order of shortest to longest (and within that, perhaps by some quality of translation measure, like number of stems or something, which we can worry about later).

**Comment by shardulc** [comment]
"We need fewer colors": I agree. The main function of the blue arrows is
that if they aren't there, then often nothing obvious will happen when the
user selects a node, which might be confusing.

"valid paths" vs. "current selected path": Sorry, I don't understand what
you're talking about. Is it that the path that is currently being used
should be shown permanently on the graph?

I disagree with not showing the "path length" because it isn't actually a
path length; if/when in the future we have actual weights to the pairs, the
total weight will be shown, which might be contrary to the actual length
ordering.

"the little caret": ? I don't think I know what this is o.O

**Comment by sushain97** [comment]
> "the little caret": ? I don't think I know what this is o.O

image

Note the small triangle shape (caret) at the bottom of the black tooltip.

> "valid paths" vs. "current selected path": Sorry, I don't understand what
you're talking about. Is it that the path that is currently being used
should be shown permanently on the graph?

I think I've forgotten how this interface actually interacts with the user. Were you able to set up Circle on your fork so that I can test it out?

**Comment by sushain97** [comment]
I changed some CircleCI settings. Try pushing to this branch again and it might build now

**Comment by shardulc** [comment]
@sushain97 [This build][1] fixes the caret issues, and handles a lot of other minor broken things too. I think whether or not to display weights is pretty much resolved. I also think the yellow endpoints and green valid path arrows are self-explanatory, but that might just be me, and the blue arrows are probably not the best idea but we need something else to indicate to the user that selecting a node actually does something.

 [1]: https://12-78226301-gh.circle-artifacts.com/0/home/circleci/project/build/index.html

**Comment by sushain97** [comment]
> the blue arrows are probably not the best idea but we need something else to indicate to the user that selecting a node actually does something.

What do you think about messing with the opacity of the edges that exist in the graph but do not belong to clicked nodes instead? i.e. they would be 50% transparent until clicked? Seems to be more natural/semantic.

**Comment by sushain97** [comment]
@shardulc could you link the latest version? Also I'm thinking that we need some brief explanatory text in the modal to explain that the workflow is 1) click nodes you want to include in the graph 2) click one of the valid paths. Otherwise, it's clear to us since we've used it multiple times but relatively unclear otherwise.

**Comment by shardulc** [comment]
@sushain97 [Here](https://13-78226301-gh.circle-artifacts.com/0/home/circleci/project/build/index.html) is a link to the latest build. Proposal for explanatory text: "Build a path for translation in the graph below by clicking on the desired intermediate languages. When a complete path is built, select it from the 'Valid Paths' list." (Would this be too much effort for localization?) I guess this should be placed above the graph.

**Comment by shardulc** [comment]
@sushain97 Thoughts about this? (There's not much left to do on the technical side so I'm trying to get this done before master accumulates other changes :P)

**Comment by sushain97** [comment]
I'll take a careful look today. Sorry for the delay!

On Nov 16, 2017 6:40 PM, "Shardul Chiplunkar" <notifications@github.com>
wrote:

@sushain97 <https://github.com/sushain97> Thoughts about this? (There's not
much left to do on the technical side so I'm trying to get this done before
master accumulates other changes :P)

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/goavki/apertium-html-tools/pull/209#issuecomment-345098660>,
or mute the thread

**Comment by IlnarSelimcan** [comment]
This feature is pretty cool and useful! Why hasn't it been enabled on beta.apertium.org?

**Comment by sushain97** [comment]
It isn't in `master`.

**Pull request merged**
